name: âš¡ï¸ Video CompressorX âš¡ï¸

on:

  schedule:

    - cron: "0 */20000 * * *"

  workflow_dispatch:

jobs:

  update:

    runs-on: ubuntu-latest

    steps:

      - name: ğŸ Set up Python 3.9 ğŸ

        uses: actions/setup-python@v2

        with:

          python-version: 3.9

      - name: ğŸŒ€ Clone the Repo ğŸŒ€

        uses: actions/checkout@master

        with:

          repository: ${{ secrets.REPO_NAME }}

      - name: ğŸ“€ Install dependencies. ğŸ“€

        run: |

          pip install wheel pyrogram tgcrypto requests spotdl yt-dlp aiofiles psutil motor dnspython

      - name: ğŸ“€ Install depenencies. ğŸ“€

        run: |
          sudo dpkg --configure -a

          apt-get install ffmpeg

      - name: ğŸƒâ€â™‚ï¸ Run the UserClient. ğŸƒâ€â™‚ï¸

        run: |

          python3 bot.py
